# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /
    weight: 10
  - name: Publicaciones
    url: publication/
    weight: 11
  - name: Charlas
    url: /#talks
    weight: 12
    weight: 13
  - name: Blog
    url: post/
    weight: 50
  - name: Docencia
    url: teaching/
    weight: 40
